stellar/stellar-anchor-tests

- .circleci/config.yml
- README.md
Add a `yarn build:all` and `yarn start:all` command for running the entire project. Updates README. Requires `yarn build:all` to succeed for CircleCI check to pass.
> update readme, add script for running ui + server

- server/Makefile
- ui/Makefile
Adding makefiles for each docker image that needs to be built. This should be the last step for enabling previews in our PR assuming the rest of the configuration files are written properly.
> Add makefiles for jenkins jobs

- ui/src/components/TestCases/SepGroupTracker.tsx
- ui/src/components/TestCases/index.tsx
- ui/src/components/TestRunner/index.tsx
- ui/src/types/testCases.ts
The purpose of this PR is to capture the progress of how many tests have been run for each sep as the results are coming in. 
With the old model, we needed to to continuously iterate over each sep group in <TestCases /> to calculate how many tests of each sep had been completed. This was causing a lot of re-rendering and was pretty inefficient. 
The solution proposed here is to capture how many tests are "done" as we collect the results in the "runTests" callback. This lets us collect all data from the results in one place.
This also has the added benefit of simplifying `<TestCases />`. Before, it was grouping `testRunArray` by sep group on every render. We, however, we were never using `testRunArray` for any purpose other than feeding it to `<TestCases />` to be coerced into a usable …
> track progress of run tests as results come in from api

- server/src/index.ts
- ui/nginx.conf
relates to stellar/kube#544
Adds a `GET /api/health` endpoint for kubernetes to use when determining if the service is up and ready to begin serving requests.
We're putting the `/health` endpoint under `/api` so the proxy server sends the request to the server container.
> add health check endpoint to server

- ui/src/components/TestRunner/index.tsx
The config file I was using wasn't properly formatted but the appropriate error was not shown. Additionally, we were not setting the `assetCode` attribute of the form data sent to the server when asset codes are initially fetched.
> Bug: check json format of config file and send assetCode in form data

- ui/src/components/TestRunnerFields/HomeDomainField.tsx
If you click "Fetch Stellar Info File" button while the field is empty, a error page is shown:
> Validate the URL and show error if invalid

- @stellar/anchor-tests/src/helpers/sep12.ts
This bug was indirectly causing the UI to show an error page, although I'm not sure why. During the debug process I noticed the request body of the "create a customer" SEP-12 test included 'url' and 'header' attributes, which lead me to this bug. After fixing, all SEP-12 tests passed and no error page was displayed.
> Only send SEP-12 request body to server, don't include 'url' and 'header' attributes

- ui/src/components/ResultBlock/index.tsx
Fixes a bug that causes the UI to crash, and adjusts the indentation of the network call content for a failed test.
While I was working on it, I noticed two other issues:
- While the length of the content window increases and decreases dynamically when opening/closing JSON objects, the initial length can sometimes be too short for requests with many headers
- Our `<ReactJson />` component fails to render response bodies from horizion and friendbot because they're technically `application/hal+json`. The content displayed instead is an error message.
I'll file issues for both of these.
> Render body as JSON component instead of passing an object as a child element

- @stellar/anchor-tests/src/helpers/test.ts
The test dependency chain maintained to detect cyclic dependency errors was not properly maintained when failures or exceptions occur for test dependencies. Popping the latest element in these cases resolves the issue.
We'll need to release a new version of the test suite library after merging.
> @stellar/anchor-tests: fix CyclicDependency false positive

- @stellar/anchor-tests/package.json
- @stellar/anchor-tests/src/helpers/test.ts
I found another issue where failed tests wouldn't be added to the `ranTests` object, which is what is used to determine if a test has already run. Omitting tests caused them to remain in the dependency chain list and cause false positive detections of cycles.
> Always mark ran tests

- @stellar/anchor-tests/package.json
- @stellar/anchor-tests/src/tests/sep12/putCustomer.ts
The SEP-12 test "memos differentiate customers registered by the same account" had a bug when checking the configuration needed for the test, causing the test to fail.
> fix same account different memos test condition

- .husky/pre-commit
- @stellar/anchor-tests/src/helpers/config.ts
- @stellar/anchor-tests/src/helpers/sep12.ts
- @stellar/anchor-tests/src/tests/sep10/tests.ts
- ui/src/components/ConfigModalContent/index.tsx
- ui/src/components/ImageUploadModalContent/index.tsx
- ui/src/components/TestRunner/index.tsx
- ui/src/components/TestRunnerFields/HomeDomainField.tsx
- ui/src/types/config.ts
- Uses the primary button variant for the 'Fetch Stellar Info File' button to match others
- Disables 'Run Tests' button if selected SEP requires a configuration file and one has not yet been uploaded
- Adds a 'Upload Customer Files' button
- Selecting the button will bring up a 'Upload Customer Files' modal presenting an explanation and form for uploading files for customers. Users can add new forms and upload N files for any customer included in their configuration file.
- Selecting 'Run Tests' sends uploaded files to the server in the expected format
- Included `.tsx` files in prettier's set of files, so thats why there are formatting changes
- Updates the version to v0.2.0
- TODO: If I'm OOO when this is merged, create a new tag and a new release of the test suite will be created
- …
> Customer File Upload Support

- @stellar/anchor-tests/package.json
- @stellar/anchor-tests/src/cli.ts
- @stellar/anchor-tests/src/helpers/console.ts
- @stellar/anchor-tests/src/helpers/test.ts
- @stellar/anchor-tests/src/schemas/config.ts
- @stellar/anchor-tests/src/schemas/sep38.ts
- @stellar/anchor-tests/src/tests/sep31/info.ts
- @stellar/anchor-tests/src/tests/sep38/getQuote.ts
- @stellar/anchor-tests/src/tests/sep38/info.ts
- @stellar/anchor-tests/src/tests/sep38/postQuote.ts
- @stellar/anchor-tests/src/tests/sep38/price.ts
- @stellar/anchor-tests/src/tests/sep38/prices.ts
- @stellar/anchor-tests/src/tests/sep38/quote.ts
- @stellar/anchor-tests/src/tests/sep38/tests.ts
- @stellar/anchor-tests/src/tests/sep38/toml.ts
- @stellar/anchor-tests/src/types.ts
- server/package.json
- ui/src/components/TestCases/SepBlock.tsx
- ui/src/components/TestCases/index.tsx
- ui/src/components/TestRunnerFields/HomeDomainField.tsx
- ui/src/helpers/testCases.ts
- ui/src/views/TestRunner.tsx
resolves #71
Adds tests to the test suite library for SEP-38.
One major assumption made by these tests is that the anchor supports clients looking to sell Stellar assets in exchange for off-chain assets, which are the types of quotes used to facilitate SEP-6/24 withdrawals and SEP-31 sends. If the anchor doesn't support these types of quotes the suite will not be very useful to them. Ideally we would check which type of exchange is supported and use those types of quotes in the rest of the tests.
> Add SEP-38 tests

- @stellar/anchor-tests/package.json
- server/src/serializers.ts
When running tests in the UI, tests are freezing because our test server is trying to clone HTTP response bodies using [clone()](https://developer.mozilla.org/en-US/docs/Web/API/Response/clone), which apparently has a [low size limit of about 16kB](https://github.com/node-fetch/node-fetch#custom-highwatermark). 
When anchors return response bodies larger than the limit, clone the body causes the process to hang. The recommended solution is to specify a larger limit, but this has to be done per-request. Because we have our `makeRequest()` helper that wouldn't be too big of a change, but we could always run into a response larger than our new limit.
Thankfully, we don't actually need to clone response bodies when serializing the results, since the response bodies will not be consumed again. …
> server: don't clone responses in serialization functions

- @stellar/anchor-tests/package.json
- @stellar/anchor-tests/src/tests/sep12/getCustomer.ts
- @stellar/anchor-tests/src/tests/sep12/putCustomer.ts
- CHANGELOG.md
SEP-12 deprecated the `account` parameter in GET and PUT endpoints. This PR removes the usage of this parameter to so anchors can test against an updated client.
> SEP-12: remove 'account' param from requests

- @stellar/anchor-tests/src/cli.ts
- CHANGELOG.md
Make sure the process exits/fails if one or more tests don't pass.
Our CI was saying the tests were successful when they were actually not passing. In order for the CI to realize the command failed, it needs to exit/fail the process with `process.exit(1)`.
> Make sure the process exits/fails if one or more tests don't pass

- @stellar/anchor-tests/package.json
- @stellar/anchor-tests/src/schemas/sep38.ts
- @stellar/anchor-tests/src/tests/sep38/postQuote.ts
- @stellar/anchor-tests/src/tests/sep38/price.ts
- @stellar/anchor-tests/src/tests/sep38/prices.ts
- @stellar/anchor-tests/src/tests/sep38/tests.ts
- CHANGELOG.md
- server/package.json
Update SEP-38 tests based on stellar/stellar-protocol#1204. The changes include:
* SEP-38 `GET /price` and `POST /quote` now require the mandatory `context` request parameter.
* SEP-38 `GET /price` and `GET|POST /quote` now return the mandatory response parameters `total_price` and `fee`.
* The updated formulas from [SEP38#price-formulas](https://github.com/stellar/stellar-protocol/blob/faa99165050dcd44a9e0f700c3d019258d8b4321/ecosystem/sep-0038.md#price-formulas) are now being validated.
> SEP-38: update SEP-38 tests based on stellar/stellar-protocol#1204

- @stellar/anchor-tests/package.json
- @stellar/anchor-tests/src/helpers/sep31.ts
- @stellar/anchor-tests/src/helpers/test.ts
- @stellar/anchor-tests/src/tests/sep31And38/tests.ts
- @stellar/anchor-tests/src/tests/sep31And38/transactions.ts
- CHANGELOG.md
- server/package.json
Specify quote_id in transaction POST request.
> Let SEP-31 POST transaction depend on SEP-38 POST quote

- @stellar/anchor-tests/package.json
- @stellar/anchor-tests/src/tests/sep12/putCustomer.ts
We weren't adding the SEP-12 `PUT /customer` requests to the test result, so when the test failed, users couldn't see the requests that failed.
> add network calls for SEP-12 test

- @stellar/anchor-tests/package.json
- @stellar/anchor-tests/src/tests/sep12/deleteCustomer.ts
- CHANGELOG.md
Found another test that didn't add its requests to the test result.
> add network calls to result again

- @stellar/anchor-tests/package.json
- @stellar/anchor-tests/src/tests/sep12/deleteCustomer.ts
- CHANGELOG.md
- server/package.json
When deleting a user, send the customer `type` if available in the customerToBeDeleted JSON.
To be compliant with SEP-12, where it says:
```text
Therefore it is recommended to always pass the `type` parameter when making requests to `GET /customer` or `PUT /customer`, even though the field is optional to accommodate for implementations that do not require type.
```
Some partners implementations require the type to be not empty, based on the statement above.
> Fix: when deleting a user, send the customer type if available in the json

- @stellar/anchor-tests/package.json
- @stellar/anchor-tests/src/schemas/sep24.ts
Relaxed SEP-24 transaction schema, as when transaction in incomplete status lots of required fields are not, in fact, required.
> Relax SEP-24 transaction schema

- @stellar/anchor-tests/src/tests/sep24/deposit.ts
The account field is made optional in SEP-24. The account assertion test should be removed.
> Remove the SEP-24 account requirement test in deposit

- @stellar/anchor-tests/package.json
Makes a patch-version bump to 0.5.8 for `@stellar/anchor-tests` package.
> bump @stellar/anchor-tests to 0.5.8

- ui/src/views/TestRunner.tsx
This check will not break the flow if `testRun` does not exist in cases where we filter out a certain group of tests. For example, 
"Account Signer Support" in SEP-10 on mainnet [here](https://github.com/stellar/stellar-anchor-tests/blob/master/%40stellar/anchor-tests/src/helpers/test.ts#L328:L334).
> Check to make sure testRun exists

- @stellar/anchor-tests/package.json
- @stellar/anchor-tests/src/schemas/sep1.ts
- @stellar/anchor-tests/src/tests/sep38/info.ts
- README.md
- server/package.json
When an anchor supports the native asset, it will add the following configurations. These are currently considered invalid by the tests.
```
[[CURRENCIES]]
code = "native"
status = "test"
is_asset_anchored = false
anchor_asset_type = "crypto"
desc = "XLM, the native token of the Stellar network."
```
This is not valid because `issuer` is required. However, `issuer` is not applicable for the native asset and can be excluded per [SEP-1](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0001.md#currency-documentation).
```
- schema: stellar
code: native
distribution_account: GBN4NNCDGJO4XW4KQU3CBIESUJWFVBUZPOKUZHT7W7WRB7CWOA7BXVQF
significant_decimals: 7
deposit:
enabled: true
max_amount: 1000000
withdraw:
enabled: true
max_amount: 1000000
send:
fee_fixed: 0
fee_percent: …
```
> [ANCHOR-305] Update tests to support stellar:native asset

- @stellar/anchor-tests/package.json
- @stellar/anchor-tests/src/tests/sep38/info.ts
- server/package.json
We should be checking `asset.asset !== "stellar:native"` not `asset !== "stellar:native:`
```
❯ yarn stellar-anchor-tests --seps 38 --home-domain http://localhost:8080 --sep-config /Users/philipliu/Documents/work/java-stellar-anchor-sdk/platform/src/test/resources/stellar-anchor-tests-sep-config.json
yarn run v1.22.19
$ node @stellar/anchor-tests/lib/cli.js --seps 38 --home-domain http://localhost:8080 --sep-config /Users/philipliu/Documents/work/java-stellar-anchor-sdk/platform/src/test/resources/stellar-anchor-tests-sep-config.json
✔ SEP-1 › TOML Tests › the TOML file exists at ./well-known/stellar.toml
✔ SEP-38 › TOML Tests › has an ANCHOR_QUOTE_SERVER attribute
failed to read keypair
failed to read keypair
✔ SEP-38 › GET /info › returns a valid info response
✔ SEP-10 › TOML Tests › …
```
> Fix stellar:native asset SEP-38 info validation

- @stellar/anchor-tests/package.json
- @stellar/anchor-tests/src/tests/sep24/transaction.ts
- server/package.json
This PR fixes a bug on the following test: `has proper withdraw transaction schema on /transaction`
It turns out that the validation of this withdraw transaction schema test was actually pointing to the `depositTransactionObj` instead of `withdrawTransactionObj` which was giving `false-positives`.
However, we also have similar test for `/transactions` endpoint (`has proper withdraw transaction schema on /transactions`) which is pointing to the correct `withdrawTransactionsObj` on its validation which appears to cover for the `/transaction` bug down the testing stack so Anchors would know at this point if there was any schema issues with withdraw transaction.
> Fix false-positive for withdraw tx schema validation on /transaction

- @stellar/anchor-tests/src/tests/sep1/tests.ts
- @stellar/anchor-tests/src/tests/sep10/tests.ts
- @stellar/anchor-tests/src/tests/sep12/toml.ts
- @stellar/anchor-tests/src/tests/sep24/toml.ts
- @stellar/anchor-tests/src/tests/sep31/toml.ts
- @stellar/anchor-tests/src/tests/sep38/toml.ts
- @stellar/anchor-tests/src/tests/sep6/toml.ts
When we run the tests from the docker container against the anchor in the host network, we will use `host.docker.internal` as the endpoint host. We need to bypass HTTPS checks for `host.docker.internal`.
> Bypass HTTPS checks with when the hostname is host.docker.internal

- @stellar/anchor-tests/package.json
- CHANGELOG.md
- server/package.json
Create release v0.5.12 to build and push the docker image to `hub.docker.com`
> Release v0.5.12

- @stellar/anchor-tests/package.json
- @stellar/anchor-tests/src/schemas/sep6.ts
- server/package.json
Some of the required fields cannot be known at the time of deposit/withdraw transaction creation. It also adds a new possible status `PENDING_CUSTOMER_INFO_UPDATE` to SEP-6 transactions, as Anchors can now decide they require more KYC info before requesting user funds.
> [ANCHOR-353] SEP-6: Fix required transaction fields

- .github/workflows/docker_publish.yml
Currently, there is a race where the Dockerhub publish completes before the npm one does, causing the image to use the older version of the test package.
Reference: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run
> Fix: Make Dockerhub publish dependent on npm publish

- @stellar/anchor-tests/README.md
- @stellar/anchor-tests/package.json
- @stellar/anchor-tests/src/tests/sep24/transaction.ts
**Description**
Disable the tests added in [PR117](https://github.com/stellar/stellar-anchor-tests/pull/117) , which are constantly failing without SEP-24 config
 **Context**
> In order to fulfill those tests Anchors will need to upload a config file in schema format with credentials and info related to existing pending and completed transactions.
For details please refer to the discussion in original PR
These PR change it to skip these tests (instead of failing) if config is not present  
**Test**
Run `yarn build:anchor-tests && yarn stellar-anchor-tests --home-domain http://localhost:8080 --seps 24 --sep-config $SEP_CONFIG`
> [ANCHOR-487] Skip failing tests that needs anchor config

- .github/workflows/docker_publish.yml
- .github/workflows/npm_and_docker_publish.yml
- @stellar/anchor-tests/package.json
Right now docker publish is not triggered by dependency `npm_publish` `completed`.
Change it to be manually invoked in `npm_publish`
> Fix `docke_publish` is not triggered by `workflow_run` action

- @stellar/anchor-tests/package.json
- @stellar/anchor-tests/src/schemas/sep6.ts
- @stellar/anchor-tests/src/tests/sep6/deposit.ts
- @stellar/anchor-tests/src/tests/sep6/withdraw.ts
- server/package.json
Anchor Platform accepts KYC asynchronously so it does not do any KYC verification before a transaction is created. This PR removes the associated tests.
> [ANCHOR-515] SEP-6: Remove KYC verification

- @stellar/anchor-tests/package.json
- @stellar/anchor-tests/src/schemas/sep6.ts
- @stellar/anchor-tests/src/tests/sep6/withdraw.ts
- server/package.json
See the [protocol change](https://github.com/stellar/stellar-protocol/pull/1417) for motivation.
This makes the `withdraw_anchor_account`, `withdraw_memo`, and `withdraw_memo` optional in the GET /transaction response. It also fixes a bug that tries to validate a `memo` even if one is not provided in the withdrawal response.
> SEP-6: Support async withdrawal instructions

- @stellar/anchor-tests/package.json
- @stellar/anchor-tests/src/schemas/sep6.ts
- @stellar/anchor-tests/src/tests/sep6/withdraw.ts
- server/package.json
The previous PR (https://github.com/stellar/stellar-anchor-tests/pull/132) did not make the `account_id` optional, which is omitted when the Anchor cannot provide the deposit address at transaction initiation.
> [Fix] SEP-6: Make `account_id` optional in withdraw response

- @stellar/anchor-tests/package.json
- @stellar/anchor-tests/src/schemas/sep31.ts
- @stellar/anchor-tests/src/tests/sep31/transactions.ts
- server/package.json
`stellar_account_id`, `stellar_memo`, and `stellar_memo_type` are optional in the POST `/transaction` response and the GET `/transaction` schema.
> Make SEP-31 transfer fields optional

- @stellar/anchor-tests/package.json
- @stellar/anchor-tests/src/tests/sep31/transactions.ts
- @stellar/anchor-tests/src/tests/sep31And38/transactions.ts
- server/package.json
A previous PR removed the requirement of `stellar_account_id`, `stellar_memo`, and `stellar_memo_type` for SEP-31 transactions. This PR removes the same requirement when the SEP-31 transaction is created with a quote.
> Fix SEP-31 transaction validation with quote

- .github/workflows/npm_and_docker_publish.yml
The `stellar/anchor-tests:v0.6.14` image uses the `0.6.13` npm package. According to GitHub Copilot, this is a consequence of Docker's caching mechanism and can be fixed by installing the latest version of the npm package first.
Since the npm package has already been published, this PR also allows the `npm publish` step to continue on error so we can rerun the job temporarily. This part will be reverted after the `0.6.14` image is fixed.
> Make npm publish idempotent

- .github/workflows/npm_and_docker_publish.yml
This fixes the following error when installing the latest version in the build.
```
Run yarn add anchor-tests@latest
yarn add v1.22.22
error Running this command will add the dependency to the workspace root rather than the workspace itself, which might not be what you want - if you really meant it, make it explicit by running this command again with the -W flag (or --ignore-workspace-root-check).
```
> Install to package workspace root

- .github/workflows/npm_and_docker_publish.yml
- Dockerfile
```
docker build . -t philip/stellar-anchor-tests
[+] Building 43.9s (12/12) FINISHED                                                                                                                                                                        docker:orbstack
=> [internal] load build definition from Dockerfile                                                                                                                                                                  0.0s
=> => transferring dockerfile: 373B                                                                                                                                                                                  0.0s
=> [internal] load metadata for docker.io/library/node:20 …
```
> Fix Dockerfile and remove build step

- .github/workflows/npm_and_docker_publish.yml
The `0.6.14` has been fixed, continuing on error is no longer necessary in the `npm publish` step.
> Remove continue-on-error in npm publish

- @stellar/anchor-tests/src/tests/sep31/info.ts
The fields object of the SEP-31 /info response is optional. However, the stellar-anchor-tests requires it.
https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0031.md#asset-object-schema
Modify the stellar-anchor-tests to optionally check the fields of the SEP-31 /info response.
> [ANCHOR-804] Make the `fields` of the SEP31 `/info` endpoint optional

- @stellar/anchor-tests/package.json
- @stellar/anchor-tests/src/schemas/sep31.ts
- @stellar/anchor-tests/src/schemas/sep6.ts
- server/package.json
Part of ticket https://stellarorg.atlassian.net/browse/ANCHOR-809
The response should looks like:
```
{
"receive": {
"JPYC": {
"enabled": true,
"quotes_supported": true,
"quotes_required": false,
"min_amount": 0,
"max_amount": 1000000,
"funding_method": ["SEPA", "SWIFT"],
"fields": { ... }
},
"USDC": {
"enabled": true,
"quotes_supported": true,
"quotes_required": false,
"min_amount": 0,
"max_amount": 10, 
"funding_method": ["SEPA", "SWIFT"],
"fields": { ... }
}
}
}
```
> [ANCHOR-809] Add `funding_method` to SEP-6/31 infoSchema

- @stellar/anchor-tests/package.json
- @stellar/anchor-tests/src/tests/sep6/info.ts
- server/package.json
The correct logic should be checking all of the required keys are provided.
Instead of checking if any provided keys is not required.
This also fix the validation test error in https://github.com/stellar/java-stellar-anchor-sdk/actions/runs/12057359373/job/33621982173?pr=1582
> [ANCHOR-809][SEP-6] Fix `/info` test logic
